ingest_url : https://ingest-url.kusto.windows.net/
client_id : client_id
client_secret : client_secret
authority : authority
database_name : database_name
table_name : table_mapping_name
table_mapping_name :
data_format : csv